### ISSUE TITLE
using root user for everything feels like it could cause issues

### ISSUE THREAD

**Issue by kevinbird15** [sparrowml/sparrow-patterns#7]
I wanted to figure out if there is any interest in making a change to sparrow-patterns to not use the root user by default.  I have been playing around with this in my fork and I think I have it mostly working although there is still one issue where I have to specify the user_id in two places, but before getting into anything too technical, is this something you would want to change or is using the root user in docker containers fine for all of your use-cases.

**Comment by jbencook** [comment]
Yes, good call @kevinbird15. I totally agree that we should stop using the root user in containers. I'll create an issue in our backlog to track this -- we can either knock it when we get to it or we'd gladly accept a contribution!

**Comment by kevinbird15** [comment]
I will give it a shot assuming you don't beat me to it.  I worked on it a little bit today.

**Comment by jbencook** [comment]
Awesome! I'm guessing it will be a while before we get to it
